from __future__ import annotations

COLOR_NAVY = "#002B6B"
COLOR_NAVY_DARK = "#001F4D"
COLOR_BLUE = "#0057E7"
COLOR_BLUE_HOVER = "#0047C2"
COLOR_BG = "#F6F8FC"
COLOR_CARD = "#FFFFFF"
COLOR_BORDER = "#E1E6F0"
COLOR_TEXT = "#0B1F4D"
COLOR_TEXT_MUTED = "#687386"
COLOR_SUCCESS = "#16A05D"
COLOR_WARNING = "#F59E0B"
COLOR_DANGER = "#E11D48"
COLOR_PURPLE = "#7C3AED"

COLOR_BLUE_SOFT = "#EAF1FF"
COLOR_SUCCESS_SOFT = "#EAF8F1"
COLOR_WARNING_SOFT = "#FFF5E6"
COLOR_DANGER_SOFT = "#FDECEF"
COLOR_PURPLE_SOFT = "#F2EAFE"

FONT_FAMILY = "Segoe UI"

MIN_WIDTH = 1400
MIN_HEIGHT = 800
SIDEBAR_WIDTH = 280
CONTENT_PADDING_X = 40
CONTENT_PADDING_Y = 32
CARD_RADIUS = 16
BUTTON_HEIGHT = 46
TABLE_ROW_HEIGHT = 52

STATUS_STYLES = {
    "Activo": (COLOR_SUCCESS, COLOR_SUCCESS_SOFT),
    "Inactivo": (COLOR_TEXT_MUTED, "#F1F3F7"),
    "Pendiente": (COLOR_WARNING, COLOR_WARNING_SOFT),
    "Asignado": (COLOR_BLUE, COLOR_BLUE_SOFT),
    "Devuelto": (COLOR_SUCCESS, COLOR_SUCCESS_SOFT),
    "Libre": (COLOR_SUCCESS, COLOR_SUCCESS_SOFT),
    "Ocupado": (COLOR_PURPLE, COLOR_PURPLE_SOFT),
    "Conflicto": (COLOR_DANGER, COLOR_DANGER_SOFT),
    "Sí": (COLOR_SUCCESS, COLOR_SUCCESS_SOFT),
    "Si": (COLOR_SUCCESS, COLOR_SUCCESS_SOFT),
    "No": (COLOR_DANGER, COLOR_DANGER_SOFT),
    "PDF listo": (COLOR_SUCCESS, COLOR_SUCCESS_SOFT),
}

CATEGORY_STYLES = {
    "Seguridad": (COLOR_BLUE, COLOR_BLUE_SOFT),
    "Vestimenta": (COLOR_PURPLE, COLOR_PURPLE_SOFT),
    "Tecnología": (COLOR_SUCCESS, COLOR_SUCCESS_SOFT),
    "Acceso": ("#B7791F", "#FFF7E6"),
    "Accesorios": ("#DB2777", "#FCEAF3"),
    "Herramienta": ("#0F766E", "#E6F7F5"),
    "Papelería": ("#475569", "#EEF2F7"),
    "Otro": (COLOR_TEXT_MUTED, "#F1F3F7"),
}
